union AliasTarget = Category | Department

enum AliasType {
  ALIAS
  PREFIX_DESCENDANTS
  POSTFIX_DESCENDANTS
}

type Alias {
  id: ID!
  target: AliasTarget!
  name: String!
  type: AliasType!
}

input AliasWhereTarget {
  eq: NodeInput
  ne: NodeInput
  in: [NodeInput!]
  nin: [NodeInput!]
}

input AliasesWhere {
  # Fields
  id: WhereId
  target: WhereNode
  name: WhereRegex
  type: AliasType

  # Logic
  and: [AliasesWhere!]
  or: [AliasesWhere!]
  nor: [AliasesWhere!]
}

extend type Query {
  alias(id: ID!): Alias
  aliases(where: AliasesWhere): [Alias!]!
}
