enum UserRole {
  SUPER_ADMIN
  USER
}

enum UserStatus {
  INVITED
  ACTIVE
  DISABLED
}

enum AccessLevel {
  VIEW
  EDIT
}

enum AuditAction {
  LOGIN
  LOGOUT
  ENTRY_CREATE
  ENTRY_UPDATE
  ENTRY_DELETE
  REFUND_CREATE
  REFUND_UPDATE
  REFUND_DELETE
  RECONCILE
  USER_INVITE
  USER_UPDATE
  USER_DELETE
  USER_DISABLE
  PERMISSION_GRANT
  PERMISSION_REVOKE
  RECEIPT_UPLOAD
  RECEIPT_DELETE
  FISCAL_YEAR_ARCHIVE
  FISCAL_YEAR_RESTORE
  FISCAL_YEAR_DELETE
}

type AuthUser {
  id: ID!
  email: String!
  googleId: String
  name: String!
  picture: String
  role: UserRole!
  status: UserStatus!
  canInviteUsers: Boolean!
  departments: [UserPermission!]!
  invitedBy: AuthUser
  invitedAt: Date
  lastLoginAt: Date
  createdAt: Date!
}

type UserPermission {
  id: ID!
  user: AuthUser!
  department: Department!
  accessLevel: AccessLevel!
  grantedBy: AuthUser!
  grantedAt: Date!
}

type AuditLogEntry {
  id: ID!
  user: AuthUser!
  action: AuditAction!
  resourceType: String
  resourceId: ID
  details: JSON
  ipAddress: String
  userAgent: String
  timestamp: Date!
}

type AuthPayload {
  token: String!
  user: AuthUser!
}

type GoogleAuthUrl {
  url: String!
}

input InviteUserPermissionInput {
  departmentId: ID!
  accessLevel: AccessLevel!
}

input InviteUserInput {
  email: String!
  name: String!
  role: UserRole
  canInviteUsers: Boolean
  permissions: [InviteUserPermissionInput!]
}

input UpdateUserInput {
  name: String
  role: UserRole
  status: UserStatus
  canInviteUsers: Boolean
}

input GrantPermissionInput {
  userId: ID!
  departmentId: ID!
  accessLevel: AccessLevel!
}

input RevokePermissionInput {
  userId: ID!
  departmentId: ID!
}

input UsersWhere {
  id: WhereId
  email: WhereRegex
  role: UserRole
  status: UserStatus
}

input AuditLogWhere {
  userId: WhereId
  action: AuditAction
  resourceType: String
  resourceId: WhereId
  timestamp: WhereDate
}

extend type Query {
  me: AuthUser
  users(where: UsersWhere): [AuthUser!]!
  user(id: ID!): AuthUser
  auditLog(where: AuditLogWhere, limit: Int, offset: Int): [AuditLogEntry!]!
  googleAuthUrl: GoogleAuthUrl!
}

extend type Mutation {
  googleAuth(code: String!): AuthPayload!
  logout: Boolean!
  inviteUser(input: InviteUserInput!): AuthUser!
  updateUser(id: ID!, input: UpdateUserInput!): AuthUser!
  deleteUser(id: ID!): Boolean!
  grantPermission(input: GrantPermissionInput!): UserPermission!
  revokePermission(input: RevokePermissionInput!): Boolean!
}
