type BackupInfo {
  filename: String!
  sizeBytes: Float!
  createdAt: Date!
  label: String!
}

type RestoreResult {
  success: Boolean!
  restoredFrom: String!
  preRestoreBackup: String!
}

type BackupCollectionCheck {
  collection: String!
  expectedCount: Int!
  actualCount: Int!
  ok: Boolean!
}

type BackupVerification {
  ok: Boolean!
  manifestFound: Boolean!
  collections: [BackupCollectionCheck!]!
}

type CreateBackupResult {
  backup: BackupInfo!
  verification: BackupVerification!
}

extend type Query {
  backups: [BackupInfo!]!
}

extend type Mutation {
  createBackup: CreateBackupResult!
  restoreBackup(filename: String!, confirmationPhrase: String!): RestoreResult!
  deleteBackup(filename: String!): Boolean!
  verifyBackup(filename: String!): BackupVerification!
}
