union BudgetOwner = Department | Business

type Budget {
  id: ID!
  amount: Rational!
  owner: BudgetOwner!
  fiscalYear: FiscalYear!
}

input BudgetsWhere {
  # Fields
  id: WhereId
  amount: WhereRational
  owner: WhereNode
  fiscalYear: FiscalYearsWhere

  # Logic
  and: [BudgetsWhere!]
  or: [BudgetsWhere!]
  nor: [BudgetsWhere!]
}

input UpsertBudget {
  id: ID
  amount: Rational!
  owner: NodeInput!
  fiscalYear: ID!
}

input DeleteBudgetInput {
  id: ID!
}

type UpsertBudgetResult {
  budget: Budget!
}

type DeleteBudgetResult {
  deletedId: ID!
}

extend type Query {
  budgets(where: BudgetsWhere): [Budget!]!
  budget(id: ID!): Budget!
}

extend type Mutation {
  upsertBudget(input: UpsertBudget!): UpsertBudgetResult!
  deleteBudget(input: DeleteBudgetInput!): DeleteBudgetResult!
}
