union BudgetOwner = Department | Business

type Budget {
  id: ID!
  amount: Rational!
  owner: BudgetOwner!
  fiscalYear: FiscalYear!
}

input BudgetsWhere {
  # Fields
  id: WhereId
  amount: WhereRational
  owner: WhereNode
  fiscalYear: FiscalYearsWhere

  # Logic
  and: [BudgetsWhere!]
  or: [BudgetsWhere!]
  nor: [BudgetsWhere!]
}

extend type Query {
  budgets(where: BudgetsWhere): [Budget!]!
  budget(id: ID!): Budget!
}
