union BudgetOwner = Department | Business

type Budget {
  id: ID!
  amount: Rational!
  owner: BudgetOwner!
  fiscalYear: FiscalYear!
}

enum BudgetOwnerType {
  BUSINESS
  DEPARTMENT
}

input BudgetOwnerInput {
  id: ID!
  type: BudgetOwnerType!
}

input BudgetsWhereOwner {
  eq: BudgetOwnerInput
  ne: BudgetOwnerInput
  in: [BudgetOwnerInput!]
  nin: [BudgetOwnerInput!]
}

input BudgetsWhereInput {
  eq: ID
  ne: ID
  in: [ID!]
  nin: [ID!]
  and: [BudgetsWhereInput!]
  or: [BudgetsWhereInput!]
  nor: [BudgetsWhereInput!]
  amount: WhereRational
  owner: BudgetsWhereOwner
  """
  Match Budgets assigned to the Department or first ancestor of the Department.
  """
  department: ID
  fiscalYear: FiscalYearWhereInput
}

extend type Query {
  budgets(where: BudgetsWhereInput): [Budget!]!
  budget(id: ID!): Budget!
}
