type Vendor {
  approved: Boolean!
  vendorId: ID
}

type Business {
  id: ID!
  name: String!
  budgets: [Budget!]!
  """
  When root is `true`, only departments who's direct parent is the the Business
  are returned.
  """
  departments(root: Boolean = false): [Department!]!
  vendor: Vendor
}

input NewBusiness {
  name: String!
}

input BusinessesWhere {
  # Fields
  id: WhereId
  name: WhereRegex

  # Logic
  and: [BusinessesWhere!]
  or: [BusinessesWhere!]
  nor: [BusinessesWhere!]
}

extend type Query {
  businesses(where: BusinessesWhere): [Business!]!
  business(id: ID!): Business!
}

extend type Mutation {
  addNewBusiness(input: NewBusiness!): Business!
}
