type Category {
  id: ID!
  name: String!
  type: EntryType!
  parent: Category
  children: [Category!]!
  aliases: [Alias!]!
}

input CategoriesWhere {
  # Fields
  id: WhereTreeId
  name: WhereRegex
  type: EntryType
  parent: WhereId

  # Logic Operators
  and: [CategoriesWhere!]
  or: [CategoriesWhere!]
  nor: [CategoriesWhere!]

  "Root Categories i.e. NO parent."
  root: Boolean
}

extend type Query {
  categories(where: CategoriesWhere): [Category!]!
  category(id: ID!): Category!
}
