type Category {
  id: ID!
  name: String!
  displayName: String!
  type: EntryType!
  parent: Category
  children: [Category!]!
  ancestors: [Category!]!
  aliases: [Alias!]!
  active: Boolean!
  hidden: Boolean
  accountNumber: String
  groupName: String
  sortOrder: Int
}

input CategoriesWhere {
  # Fields
  id: WhereTreeId
  name: WhereRegex
  type: EntryType
  parent: WhereId
  active: Boolean
  hidden: Boolean
  groupName: WhereRegex

  # Logic Operators
  and: [CategoriesWhere!]
  or: [CategoriesWhere!]
  nor: [CategoriesWhere!]

  "Root Categories i.e. NO parent."
  root: Boolean
}

input UpdateCategoryInput {
  hidden: Boolean
  name: String
  displayName: String
  groupName: String
  sortOrder: Int
}

type UpdateCategoryPayload {
  category: Category!
}

extend type Query {
  categories(where: CategoriesWhere): [Category!]!
  category(id: ID!): Category!
  categoryGroups: [String!]!
}

extend type Mutation {
  updateCategory(id: ID!, input: UpdateCategoryInput!): UpdateCategoryPayload!
}
