union DepartmentAncestor = Department | Business

type Department {
  id: ID!
  name: String!
  code: String
  budgets: [Budget!]!
  business: Business!
  parent: DepartmentAncestor!
  children: [Department!]!
  disable: [FiscalYear!]!
  ancestors(
    """
    Set an alterative root for the `ancestor` path.
    Default: `Business`.
    Behavior: ancestors <= the shortest path to an ancestor matched by `DepartmentsWhere`.  If no ancestors are matched in the path, no ancestors are returned i.e. the `Department` is outside of the new root's tree.
    """
    root: DepartmentsWhere
  ): [DepartmentAncestor!]!
  descendants: [Department!]!
  virtualRoot: Boolean
  aliases: [Alias!]!
}

input DepartmentsWhere {
  # Felids
  id: WhereTreeId
  name: WhereRegex
  code: String
  parent: WhereNode
  "Matches all departments that are a decedents of the business."
  business: ID

  # Logic Operators
  and: [DepartmentsWhere!]
  or: [DepartmentsWhere!]
  nor: [DepartmentsWhere!]
}

type Query {
  departments(where: DepartmentsWhere): [Department!]!
  department(id: ID!): Department!
}
