union DepartmentAncestor = Department | Business

type Department {
  id: ID!
  name: String!
  code: String
  """
  Budgets are the FIRST Budget per FiscalYear assigned to
  the Department or an ancestor of the Department.
  """
  budgets: [Budget!]!
  business: Business!
  parent: DepartmentAncestor!
  ancestors: [DepartmentAncestor!]!
  descendants: [Department!]!
  virtualRoot: Boolean
}

enum DepartmentAncestorType {
  BUSINESS
  DEPARTMENT
}

input DepartmentAncestorInput {
  id: ID!
  type: DepartmentAncestorType!
}

input DepartmentsWhereAncestor {
  eq: DepartmentAncestorInput
  ne: DepartmentAncestorInput
  in: [DepartmentAncestorInput!]
  nin: [DepartmentAncestorInput!]
}

input DepartmentsWhereInput {
  eq: ID
  ne: ID
  in: [ID!]
  nin: [ID!]
  name: WhereRegexInput
  parent: DepartmentsWhereAncestor
  and: [DepartmentsWhereInput!]
  or: [DepartmentsWhereInput!]
  nor: [DepartmentsWhereInput!]
}

input DepartmentAddFields {
  name: String!
}

type Query {
  departments(where: DepartmentsWhereInput): [Department!]!
  department(id: ID!): Department!
}
