"""
Enforces mutual exclusion of fields.
"""
directive @mutexFields(
  """
  Sets of mutually exclusive fields. Default: All Fields
  """
  fieldGroups: [[String!]!]
) on INPUT_OBJECT

"""
Requires at least one field.  Input Object Required Fields are ignored.
"""
directive @requireOneField(
  """
  Sets of fields in which one is required. Default: One of All fields
  """
  fieldGroups: [[String!]!]
) on INPUT_OBJECT
