type FiscalYear {
  id: ID!
  name: String!
  begin: String!
  end: String!
}

input FiscalYearWhereHasDate {
  eq: String
  ne: String
  in: [String!]
  nin: [String!]
}

input FiscalYearWhereInput {
  eq: ID
  ne: ID
  in: [ID!]
  nin: [ID!]
  name: WhereRegexInput
  """
  A FiscalYear is the set of all dates in the interval [begin, end).
  """
  hasDate: FiscalYearWhereHasDate
  and: [FiscalYearWhereInput!]
  or: [FiscalYearWhereInput!]
  nor: [FiscalYearWhereInput!]
}

extend type Query {
  fiscalYears(where: FiscalYearWhereInput): [FiscalYear!]!
  fiscalYear(id: ID!): FiscalYear!
}
