type FiscalYear {
  id: ID!
  name: String!
  begin: Date!
  end: Date!
}

input FiscalYearsWhere {
  # Fields
  id: WhereId
  name: WhereRegex
  """
  A FiscalYear is the set of all dates in the interval [begin, end).
    eq: A fiscal year that contains the date.
    ne: Any fiscal year that does NOT contain the date.
    gt: Any fiscal year that begins after the date.
    gte: Any fiscal year that contains the date or begins after the date.
    lt: Any fiscal year that ends on or before the date.
    lte: Any fiscal year that contains the date or ends on or before the date.
  """
  date: WhereDate

  # Logic
  and: [FiscalYearsWhere!]
  or: [FiscalYearsWhere!]
  nor: [FiscalYearsWhere!]
}

input CreateFiscalYearInput {
  name: String!
  begin: Date!
  end: Date!
}

type CreateFiscalYearPayload {
  fiscalYear: FiscalYear!
}

extend type Query {
  fiscalYears(where: FiscalYearsWhere): [FiscalYear!]!
  fiscalYear(id: ID!): FiscalYear!
}

extend type Mutation {
  createFiscalYear(input: CreateFiscalYearInput!): CreateFiscalYearPayload!
}
