enum JournalEntryType {
  CREDIT
  DEBIT
}

type JournalEntry {
  id: ID!
  refunds: [JournalEntryRefund!]!
  items: [JournalEntryItem!]!
  type: JournalEntryType!
  date: String!
  department: Department!
  category: JournalEntryCategory!
  paymentMethod: PaymentMethod!
  description: String
  total: Rational!
  source: JournalEntrySource!
  reconciled: Boolean!
  lastUpdate: String!
  deleted: Boolean!
}

enum JournalEntrySourceType {
  BUSINESS
  DEPARTMENT
  PERSON
}

input JournalEntrySourceInput {
  sourceType: JournalEntrySourceType!
  id: ID!
}

input JournalEntryUpdateFields {
  date: String
  department: ID
  type: JournalEntryType
  category: ID
  paymentMethod: ID
  description: String
  total: RationalInput
  source: JournalEntrySourceInput
  reconciled: Boolean
}

input JournalEntryAddFields {
  date: String!
  department: ID!
  type: JournalEntryType!
  category: ID!
  paymentMethod: ID!
  description: String
  total: RationalInput!
  source: JournalEntrySourceInput!
  reconciled: Boolean
}

# Refunds
type JournalEntryRefund {
  id: ID!
  date: String!
  description: String
  paymentMethod: PaymentMethod!
  total: Rational!
  reconciled: Boolean!
  lastUpdate: String!
  deleted: Boolean!
}

input JournalEntryAddRefundFields {
  date: String!
  description: String
  paymentMethod: ID!
  total: RationalInput!
  reconciled: Boolean
}

input JournalEntryUpdateRefundFields {
  date: String
  description: String
  paymentMethod: ID
  total: RationalInput
  reconciled: Boolean
}

# Items
type JournalEntryItem {
  id: ID!
  department: Department
  category: JournalEntryCategory
  description: String
  total: Rational!
  lastUpdate: String!
  deleted: Boolean!
}

input JournalEntryAddItemFields {
  department: ID
  category: ID
  description: String
  total: RationalInput!
}

input JournalEntryUpdateItemFields {
  department: ID
  category: ID
  description: String
  total: RationalInput
}

type JournalEntryItemUpsertResult {
  journalEntryItem: JournalEntryItem!
  journalEntry: JournalEntry!
}

# Where
input JournalEntriesWhereDepartment {
  eq: ID
  ne: ID
  in: [ID]
  nin: [ID]
  matchDecedentTree: Boolean
}

input JournalEntriesWhereLastUpdate {
  gt: String
  lt: String
  gte: String
  lte: String
}

input JournalEntiresWhereInput {
  department: JournalEntriesWhereDepartment
  reconciled: Boolean
  deleted: Boolean
  lastUpdate: JournalEntriesWhereLastUpdate
  lastUpdateRefund: JournalEntriesWhereLastUpdate
  lastUpdateItem: JournalEntriesWhereLastUpdate
  or: [JournalEntiresWhereInput]
  and: [JournalEntiresWhereInput]
}

type Query {
  journalEntries(where: JournalEntiresWhereInput): [JournalEntry!]!
  journalEntry(id: ID!): JournalEntry
  journalEntryRefund(id: ID!): JournalEntryRefund
  journalEntryItem(id: ID!): JournalEntryItem
}

input JournalEntryUpdatePaymentMethod {
  id: ID!
  fields: PaymentMethodUpdateFields!
}

type Mutation {
  journalEntryUpdate(
    id: ID!
    fields: JournalEntryUpdateFields!
    paymentMethodAdd: PaymentMethodAddFields
    paymentMethodUpdate: JournalEntryUpdatePaymentMethod
    personAdd: PersonAddFields
    businessAdd: BusinessAddFields
  ): JournalEntry!
  journalEntryAdd(
    fields: JournalEntryAddFields!
    paymentMethodAdd: PaymentMethodAddFields
    personAdd: PersonAddFields
    businessAdd: BusinessAddFields
  ): JournalEntry!
  journalEntryDelete(id: ID!): JournalEntry!
  journalEntryAddRefund(
    id: ID!
    fields: JournalEntryAddRefundFields!
    paymentMethodAdd: PaymentMethodAddFields
  ): JournalEntry!
  journalEntryUpdateRefund(
    id: ID!
    fields: JournalEntryUpdateRefundFields!
    paymentMethodAdd: PaymentMethodAddFields
    paymentMethodUpdate: JournalEntryUpdatePaymentMethod
  ): JournalEntry!
  journalEntryDeleteRefund(id: ID!): JournalEntry!
  journalEntryAddItem(
    id: ID!
    fields: JournalEntryAddItemFields!
  ): JournalEntryItemUpsertResult!
  journalEntryUpdateItem(
    id: ID!
    fields: JournalEntryUpdateItemFields!
  ): JournalEntryItemUpsertResult!
  journalEntryDeleteItem(id: ID!): JournalEntryItemUpsertResult!
}

type Subscription {
  journalEntryAdded: JournalEntry!
  journalEntryUpdated: JournalEntry!
  journalEntryUpserted: JournalEntry!
}
