enum JournalEntryType {
  CREDIT
  DEBIT
}

type JournalEntry {
  id:ID!
  type:JournalEntryType!
  date:String!
  department:Department!
  category:JournalEntryCategory!
  paymentMethod:PaymentMethod!
  description:String
  total:Rational!
  source:JournalEntrySource!
  reconciled:Boolean!
}

enum JournalEntrySourceType {
  BUSINESS
  DEPARTMENT
  PERSON
}

input JournalEntrySourceInput {
  sourceType:JournalEntrySourceType!
  id:ID!
}

input JournalEntryUpdateFields {
  date:String
  department:ID
  type:JournalEntryType
  category:ID
  paymentMethod:ID
  description:String
  total:RationalInput
  source:JournalEntrySourceInput
  reconciled:Boolean
}

input JournalEntryAddFields {
  date:String!
  department:ID!
  type:JournalEntryType!
  category:ID!
  paymentMethod:ID!
  description:String
  total:RationalInput!
  source:JournalEntrySourceInput!
  reconciled:Boolean
}

enum JournalEntriesColumn {
  DEPARTMENT
  TYPE
  CATEGORY
  # ROOT_TYPE
  PAYMENT_METHOD
  TOTAL
  DATE
  SOURCE
}

input JournalEntriesSortByInput {
  column:JournalEntriesColumn!
  direction:SortDirection = ASC
}

enum JournalEntiresReconciledFilter {
  RECONCILED
  NOT_RECONCILED
}

input JournalEntiresFilterInput {
  department:ByIdFilter
  reconciled:JournalEntiresReconciledFilter
}

type JournalEntriesRes {
  totalCount:Int!
  entries:[JournalEntry!]!
}

type JournalEntryAddedRes {
   totalCount:Int!
   index:Int!
   entry:JournalEntry!
}

type Query {
  journalEntries(paginate:PaginateInput, sortBy:[JournalEntriesSortByInput!],
    filterBy:JournalEntiresFilterInput):JournalEntriesRes!
}

type Mutation {
  updateJournalEntry(id:ID!, fields:JournalEntryUpdateFields!):
    JournalEntry!
  addJournalEntry(fields:JournalEntryAddFields!):JournalEntry!
}

type Subscription {
    journalEntryAdded:JournalEntry!
    journalEntryUpdated:JournalEntry!
}