# Cards
enum PaymentCardType {
  VISA
  MASTER_CARD
  AMERICAN_EXPRESS
  DISCOVER
}

interface PaymentCardInterface {
  trailingDigits: String!
  type: PaymentCardType!
}

type PaymentCard implements PaymentCardInterface {
  trailingDigits: String!
  type: PaymentCardType!
}

input PaymentCardInput {
  trailingDigits: String!
  type: PaymentCardType!
}

# Checks
interface PaymentCheckInterface {
  checkNumber: String!
}

type PaymentCheck implements PaymentCheckInterface {
  checkNumber: String!
}

input PaymentCheckInput {
  checkNumber: String!
}

# Base Payment Method
interface PaymentMethodInterface {
  currency: Currency!
}

type PaymentMethodCard implements PaymentMethodInterface {
  card: PaymentCardInterface!
  currency: Currency!
}

input PaymentMethodCardInput {
  card: PaymentCardInput!
  currency: Currency!
}

input PaymentMethodAccountCardInput {
  """
  id from AccountCard
  """
  card: ID!
  currency: Currency!
}

type PaymentMethodCheck implements PaymentMethodInterface {
  currency: Currency!
  check: PaymentCheckInterface!
}

input PaymentMethodCheckInput {
  currency: Currency!
  check: PaymentCheckInput!
}

input PaymentMethodAccountCheckInput {
  currency: Currency!
  check: AccountCheckInput!
}

type PaymentMethodCash implements PaymentMethodInterface {
  currency: Currency!
}

input PaymentMethodCashInput {
  currency: Currency!
}

type PaymentMethodOnline implements PaymentMethodInterface {
  currency: Currency!
}

input PaymentMethodOnlineInput {
  currency: Currency!
}

type PaymentMethodCombination implements PaymentMethodInterface {
  currency: Currency!
}

input PaymentMethodCombinationInput {
  currency: Currency!
}

type PaymentMethodUnknown implements PaymentMethodInterface {
  currency: Currency!
}

input PaymentMethodUnknownInput {
  currency: Currency!
}

enum PaymentMethodType {
  CARD
  CHECK
  CASH
  ONLINE
  COMBINATION
  UNKNOWN
}

"""
One field is required and fields are mutually exclusive..
"""
input UpsertPaymentMethod {
  card: PaymentMethodCardInput
  accountCard: PaymentMethodAccountCardInput
  check: PaymentMethodCheckInput
  accountCheck: PaymentMethodAccountCheckInput
  cash: PaymentMethodCashInput
  online: PaymentMethodOnlineInput
  combination: PaymentMethodCombinationInput
  unknown: PaymentMethodUnknownInput
}
