# union PaymentMethodAuthorizedEntity = Person | Business | Department

# type PaymentMethodAuthorization {
#   owner: Boolean!
#   entity: PaymentMethodAuthorizedEntity
# }

type PaymentMethod {
  id: ID!
  active: Boolean!
  refId: String
  name: String!
  parent: PaymentMethod
  children: [PaymentMethod!]!
  allowChildren: Boolean!
  # authorization: [PaymentMethodAuthorization!]!
}

input PaymentMethodWhereParentInput {
  eq: ID
  ne: ID
  in: [ID]
  nin: [ID]
}

input PaymentMethodWhereRefIdInput {
  eq: String
  ne: String
  in: [String]
  nin: [String]
}

input PaymentMethodWhereNameInput {
  eq: String
  ne: String
  in: [String]
  nin: [String]
}

input PaymentMethodWhereInput {
  active: Boolean
  refId: PaymentMethodWhereRefIdInput
  name: PaymentMethodWhereNameInput
  hasParent: Boolean
  parent: PaymentMethodWhereParentInput
  or: [PaymentMethodWhereInput]
  and: [PaymentMethodWhereInput]
}

input PaymentMethodWhere {
  # Fields
  id: WhereTreeId
  active: Boolean
  name: WhereRegex
  parent: WhereId
  allowChildren: Boolean

  # Logic
  and: [PaymentMethodWhere!]
  or: [PaymentMethodWhere!]
  nor: [PaymentMethodWhere!]
}

input PaymentMethodAddFields {
  active: Boolean!
  refId: String
  name: String!
  parent: ID! # Do NOT allow root level payment methods
}

input PaymentMethodUpdateFields {
  active: Boolean
  refId: String
  name: String
}

extend type Query {
  paymentMethods(where: PaymentMethodWhere): [PaymentMethod!]!
  paymentMethod(id: ID!): PaymentMethod
}

extend type Mutation {
  paymentMethodUpdate(
    id: ID!
    fields: PaymentMethodUpdateFields!
  ): PaymentMethod!
  paymentMethodAdd(fields: PaymentMethodAddFields!): PaymentMethod!
}
