type PersonName {
  first: String!
  last: String!
}

input PersonNameInput {
  first: String!
  last: String!
}

input NewPerson {
  name: PersonNameInput!
  email: String
  phone: String
}

type AddNewPersonPayload {
  newPerson: Person!
}

type Person {
  id: ID!
  name: PersonName!
}

input PeopleNameWhere {
  first: WhereRegex
  last: WhereRegex
}

input PeopleWhere {
  # Fields
  id: WhereId
  name: PeopleNameWhere

  # Logical
  and: [PeopleWhere!]
  or: [PeopleWhere!]
  nor: [PeopleWhere!]
}

extend type Query {
  people(where: PeopleWhere): [Person!]!
  person(id: ID!): Person!
}

extend type Mutation {
  addNewPerson(input: NewPerson!): AddNewPersonPayload!
}
