type PersonName {
  first: String!
  last: String!
}

input PersonNameInput {
  first: String!
  last: String!
}

input NewPerson {
  name: PersonNameInput!
  email: String
  phone: String
}

type AddNewPersonPayload {
  newPerson: Person!
}

type Person {
  id: ID!
  name: PersonName!
  email: String
  phone: String
  hidden: Boolean
}

input PeopleNameWhere {
  first: WhereRegex
  last: WhereRegex
}

input PeopleWhere {
  # Fields
  id: WhereId
  name: PeopleNameWhere
  hidden: Boolean

  # Logical
  and: [PeopleWhere!]
  or: [PeopleWhere!]
  nor: [PeopleWhere!]
}

input UpdatePersonInput {
  hidden: Boolean
  name: PersonNameInput
  email: String
  phone: String
}

type UpdatePersonPayload {
  person: Person!
}

extend type Query {
  people(where: PeopleWhere): [Person!]!
  person(id: ID!): Person!
}

extend type Mutation {
  addNewPerson(input: NewPerson!): AddNewPersonPayload!
  updatePerson(id: ID!, input: UpdatePersonInput!): UpdatePersonPayload!
}
