scalar Rational

input WhereRational {
  eq: Rational
  ne: Rational
  in: [Rational!]
  nin: [Rational!]
  gt: Rational
  lt: Rational
  gte: Rational
  lte: Rational
}

"""
Date Constraints
"""
directive @rationalConstraint(
  eq: Float
  ne: Float
  gt: Float
  gte: Float
  lt: Float
  lte: Float
) on FIELD_DEFINITION | INPUT_FIELD_DEFINITION
