enum RationalSign {
  POS
  NEG
}
type Rational {
  n: Int!
  d: Int!
  s: RationalSign!
}

input RationalInput {
  n: Int!
  d: Int!
  s: RationalSign!
}

input WhereRational {
  eq: RationalInput
  ne: RationalInput
  in: [RationalInput!]
  nin: [RationalInput!]
  gt: RationalInput
  lt: RationalInput
  gte: RationalInput
  lte: RationalInput
}
