enum SortDirection {
  ASC
  DESC
}

enum FilterType {
  INCLUDE
  EXCLUDE
}

input PaginateInput {
  skip: Int!
  limit: Int!
}

input ByIdFilter {
  eq: ID
}

enum RegexOptions {
  CaseInsensitive
  Multiline
  Extended
  DotAll
  I
  M
  X
  S
}

input WhereTreeNodeInput {
  id: ID!
  matchDescendants: Boolean
}

input WhereRegexInput {
  pattern: String!
  options: [RegexOptions!]
}

input WhereDateTime {
  """
  ISO 8601
  """
  date: String!
  ignoreTime: Boolean
}

input WhereDate {
  eq: WhereDateTime
  ne: WhereDateTime
  gt: WhereDateTime
  gte: WhereDateTime
  lt: WhereDateTime
  lte: WhereDateTime
}
