input WhereId {
  eq: ID
  ne: ID
  in: [ID!]
  nin: [ID!]
}

input WhereTreeId {
  eq: ID
  ne: ID
  in: [ID!]
  nin: [ID!]
  """
  Range operators will match descendants and ancestors in the tree.
  """
  gt: ID
  gte: ID
  lt: ID
  lte: ID
}

input NodeInput {
  type: String!
  id: ID!
}

input WhereNode {
  eq: NodeInput
  ne: NodeInput
  in: [NodeInput!]
  nin: [NodeInput!]
}

"""
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#advanced_searching_with_flags
"""
enum RegexFlags {
  "Global search."
  G
  "Case-insensitive search."
  I
  "Multi-line search."
  M
  "Allows . to match newline characters."
  S
}

input WhereRegex {
  """
  "pattern" argument of the javascript RegExp constructor.
  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/RegExp#parameters
  """
  pattern: String!
  flags: [RegexFlags!]
}

input WhereInt {
  eq: Int
  ne: Int
  gt: Int
  gte: Int
  lt: Int
  lte: Int
}

input WhereDate {
  eq: Date
  ne: Date
  gt: Date
  gte: Date
  lt: Date
  lte: Date
}

"""
The Upload scalar type represents a file upload.
Used with graphql-upload for handling multipart file uploads.
"""
scalar Upload

"""
The JSON scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON
